import { randomInt, randomUUID } from 'node:crypto';

const caseScript = cases => cases.map(([input, expected]) => ({ input: String(input), expression: '', expected: String(expected) }));
const caseFunction = cases => cases.map(([expression, expected]) => ({ input: '', expression, expected: JSON.stringify(expected) }));
const script = (title, statement, inputFormat, outputFormat, reference, hints, cases, constraints = 'Dữ liệu đầu vào hợp lệ.') => ({
  title, statement, inputFormat, outputFormat, constraints, mode: 'script', starter: '# Viết chương trình ở đây\n', reference,
  hints, rubric: ['Đọc và chuyển kiểu dữ liệu đúng.', 'Tính toán đúng theo yêu cầu.', 'In kết quả đúng định dạng.'], tests: caseScript(cases)
});
const func = (title, statement, name, params, reference, hints, cases, outputFormat = 'Giá trị trả về đúng theo đề bài.') => ({
  title, statement, inputFormat: `Hệ thống gọi ${name}(${params}).`, outputFormat, constraints: 'Viết đúng tên hàm, tham số và dùng return; không đọc input hoặc in kết quả bên trong hàm.',
  mode: 'function', starter: `def ${name}(${params}):\n    # Viết lời giải ở đây\n    pass\n`, reference, hints,
  rubric: ['Đúng tên hàm và tham số.', 'Trả kết quả bằng return.', 'Xử lý đúng các trường hợp biên.'], tests: caseFunction(cases)
});

// Mỗi danh sách dưới đây là 10 bài đã biên soạn cho đúng phạm vi nhập môn Python.
const bank = {
  variables: [
    script('Tổng hai khoản thu', 'Nhập hai khoản thu x, y. In tổng của chúng.', '2 dòng: x và y.', 'Một số thực.', 'x = float(input())\ny = float(input())\nprint(x + y)', ['Đọc mỗi dòng bằng float().', 'Cộng hai biến rồi in kết quả.'], [['12\n8', 20], ['0.5\n1.25', 1.75], ['-3\n7', 4]]),
    script('Chênh lệch doanh thu', 'Nhập doanh thu kỳ này và kỳ trước. In mức tăng/giảm tuyệt đối (kỳ này trừ kỳ trước).', '2 dòng: kỳ này, kỳ trước.', 'Một số thực.', 'now = float(input())\nold = float(input())\nprint(now - old)', ['Gán từng dòng cho một biến.', 'Lấy kỳ này trừ kỳ trước.'], [['120\n100', 20], ['90\n100', -10], ['50\n50', 0]]),
    script('Giá trị lô hàng', 'Nhập đơn giá và số lượng sản phẩm. In tổng giá trị lô hàng.', '2 dòng: đơn giá, số lượng.', 'Một số thực.', 'price = float(input())\nquantity = int(input())\nprint(price * quantity)', ['Chú ý số lượng là số nguyên.', 'Giá trị bằng đơn giá nhân số lượng.'], [['12500\n4', 50000], ['0\n9', 0], ['2.5\n6', 15]]),
    script('Giá sau giảm giá', 'Nhập giá niêm yết và phần trăm giảm giá. In giá sau giảm.', '2 dòng: giá, phần trăm giảm.', 'Một số thực, làm tròn 2 chữ số.', 'price = float(input())\ndiscount = float(input())\nprint(f"{price * (1 - discount / 100):.2f}")', ['Đổi phần trăm thành số thập phân.', 'Giá mới = giá × (1 - tỷ lệ giảm).'], [['200\n10', '180.00'], ['50\n0', '50.00'], ['80\n100', '0.00']]),
    script('Tiền hàng và VAT', 'Nhập giá trị trước thuế và thuế suất VAT. In tổng tiền sau thuế.', '2 dòng: tiền hàng, VAT (%).', 'Một số thực, làm tròn 2 chữ số.', 'amount = float(input())\nvat = float(input())\nprint(f"{amount * (1 + vat / 100):.2f}")', ['VAT được tính trên tiền hàng.', 'Nhân tiền hàng với 1 + VAT/100.'], [['1000\n10', '1100.00'], ['250\n8', '270.00'], ['0\n10', '0.00']]),
    script('Giá trung bình', 'Nhập giá của ba mặt hàng. In giá trung bình.', '3 dòng: ba mức giá.', 'Một số thực, làm tròn 2 chữ số.', 'a = float(input())\nb = float(input())\nc = float(input())\nprint(f"{(a + b + c) / 3:.2f}")', ['Cộng cả ba mức giá.', 'Chia tổng cho 3.'], [['10\n20\n30', '20.00'], ['1\n1\n2', '1.33'], ['0\n0\n0', '0.00']]),
    script('Đổi ngoại tệ', 'Nhập số tiền USD và tỷ giá VND/USD. In số tiền VND tương ứng.', '2 dòng: USD, tỷ giá.', 'Một số thực, làm tròn 2 chữ số.', 'usd = float(input())\nrate = float(input())\nprint(f"{usd * rate:.2f}")', ['Số tiền VND bằng USD nhân tỷ giá.', 'Dùng :.2f để định dạng.'], [['10\n25000', '250000.00'], ['0\n25000', '0.00'], ['2.5\n24000', '60000.00']]),
    script('Doanh thu bình quân mỗi sản phẩm', 'Nhập tổng doanh thu và số sản phẩm đã bán. In doanh thu trung bình một sản phẩm.', '2 dòng: doanh thu, số lượng (số lượng > 0).', 'Một số thực, làm tròn 2 chữ số.', 'revenue = float(input())\nquantity = int(input())\nprint(f"{revenue / quantity:.2f}")', ['Lấy tổng doanh thu chia số lượng.', 'Định dạng kết quả hai chữ số thập phân.'], [['100\n4', '25.00'], ['10\n3', '3.33'], ['0\n5', '0.00']]),
    script('Lương sau thưởng', 'Nhập lương cơ bản và phần trăm thưởng. In tổng lương sau khi cộng thưởng.', '2 dòng: lương cơ bản, thưởng (%).', 'Một số thực, làm tròn 2 chữ số.', 'salary = float(input())\nbonus = float(input())\nprint(f"{salary * (1 + bonus / 100):.2f}")', ['Tính tỷ lệ thưởng từ lương cơ bản.', 'Cộng thưởng bằng cách nhân 1 + tỷ lệ.'], [['10000000\n5', '10500000.00'], ['8000000\n0', '8000000.00'], ['100\n12.5', '112.50']]),
    script('Chu vi và diện tích hình chữ nhật', 'Nhập chiều dài, chiều rộng. In chu vi rồi diện tích, mỗi kết quả một dòng.', '2 dòng: dài, rộng.', '2 dòng: chu vi và diện tích.', 'd = float(input())\nr = float(input())\nprint(2 * (d + r))\nprint(d * r)', ['Chu vi bằng 2 × (dài + rộng).', 'Diện tích bằng dài × rộng.'], [['4\n3', '14\n12'], ['1.5\n2', '7.0\n3.0'], ['0\n5', '10\n0']])
  ],
  sequences: [
    script('Tổng doanh thu', 'Nhập một dòng gồm các số doanh thu. In tổng các phần tử.', 'Một dòng số nguyên cách nhau bởi dấu cách.', 'Một số nguyên.', 'a = list(map(int, input().split()))\nprint(sum(a))', ['Dùng split() và map(int, ...).', 'sum() tính tổng danh sách.'], [['1 2 3', 6], ['0 0', 0], ['10 20 5', 35]]),
    script('Doanh thu cao nhất', 'Nhập danh sách doanh thu. In giá trị lớn nhất.', 'Một dòng gồm ít nhất một số nguyên.', 'Một số nguyên.', 'a = list(map(int, input().split()))\nprint(max(a))', ['Tách dòng thành danh sách số nguyên.', 'Dùng max() để tìm giá trị lớn nhất.'], [['1 9 3', 9], ['-5 -2 -8', -2], ['7', 7]]),
    script('Doanh thu thấp nhất', 'Nhập danh sách doanh thu. In giá trị nhỏ nhất.', 'Một dòng gồm ít nhất một số nguyên.', 'Một số nguyên.', 'a = list(map(int, input().split()))\nprint(min(a))', ['Dùng min() trên danh sách.', 'Danh sách đảm bảo không rỗng.'], [['1 9 3', 1], ['-5 -2 -8', -8], ['7', 7]]),
    script('Đếm giao dịch dương', 'Nhập danh sách giá trị giao dịch. Đếm số giao dịch có giá trị lớn hơn 0.', 'Một dòng số thực cách nhau bởi dấu cách.', 'Một số nguyên.', 'a = list(map(float, input().split()))\nprint(sum(x > 0 for x in a))', ['Duyệt từng phần tử trong danh sách.', 'Đếm phần tử thỏa điều kiện x > 0.'], [['1 -2 0 4', 2], ['-1 -2', 0], ['3', 1]]),
    script('Đếm số chẵn', 'Nhập danh sách số nguyên. In số lượng phần tử chẵn.', 'Một dòng số nguyên cách nhau bởi dấu cách.', 'Một số nguyên.', 'a = list(map(int, input().split()))\nprint(sum(x % 2 == 0 for x in a))', ['Số chẵn có x % 2 == 0.', 'Cộng số điều kiện đúng.'], [['1 2 4 7', 2], ['1 3 5', 0], ['0 -2', 2]]),
    script('Điểm trung bình', 'Nhập danh sách điểm. In điểm trung bình với 2 chữ số thập phân.', 'Một dòng điểm cách nhau bởi dấu cách.', 'Một số thực, làm tròn 2 chữ số.', 'a = list(map(float, input().split()))\nprint(f"{sum(a) / len(a):.2f}")', ['Tổng điểm chia số lượng điểm.', 'len() trả về số phần tử.'], [['7 8 9', '8.00'], ['1 2', '1.50'], ['10', '10.00']]),
    script('Số mã hàng khác nhau', 'Nhập danh sách mã hàng dạng số. In số lượng giá trị khác nhau.', 'Một dòng số nguyên cách nhau bởi dấu cách.', 'Một số nguyên.', 'a = list(map(int, input().split()))\nprint(len(set(a)))', ['set() loại các giá trị trùng.', 'Đếm phần tử của set bằng len().'], [['1 1 2 3', 3], ['5 5 5', 1], ['1 2 3', 3]]),
    script('Thêm một giao dịch', 'Nhập danh sách số nguyên và số x. Thêm x vào cuối danh sách rồi in danh sách mới trên một dòng.', 'Dòng 1: danh sách số nguyên. Dòng 2: x.', 'Các số sau khi thêm, cách nhau bởi dấu cách.', 'a = list(map(int, input().split()))\nx = int(input())\na.append(x)\nprint(*a)', ['Đọc dòng đầu thành list.', 'append(x) thêm phần tử cuối danh sách.', 'print(*a) in các phần tử cách nhau bởi dấu cách.'], [['1 2 3\n4', '1 2 3 4'], ['0\n-1', '0 -1'], ['5 5\n5', '5 5 5']]),
    script('Sắp xếp giá theo thứ tự tăng', 'Nhập danh sách giá nguyên. In các giá theo thứ tự tăng dần.', 'Một dòng số nguyên cách nhau bởi dấu cách.', 'Một dòng số nguyên cách nhau bởi dấu cách.', 'a = list(map(int, input().split()))\na.sort()\nprint(*a)', ['Dùng sort() để sắp xếp tại chỗ.', 'In danh sách với toán tử *.'], [['3 1 2', '1 2 3'], ['5 5 1', '1 5 5'], ['-1 0', '-1 0']]),
    script('Đếm ký tự trong mã đơn', 'Nhập chuỗi mã đơn và một ký tự. Đếm số lần ký tự đó xuất hiện.', 'Dòng 1: chuỗi. Dòng 2: một ký tự.', 'Một số nguyên.', 'text = input()\nch = input()\nprint(text.count(ch))', ['Chuỗi cũng là một cấu trúc tuần tự.', 'Dùng count() để đếm ký tự.'], [['banana\na', 3], ['NEU\nX', 0], ['11101\n1', 4]])
  ],
  conditions: [
    script('Chẵn hay lẻ', 'Nhập số nguyên n. In Chan nếu n chẵn, nếu không in Le.', 'Một số nguyên.', 'Chan hoặc Le.', 'n = int(input())\nif n % 2 == 0:\n    print("Chan")\nelse:\n    print("Le")', ['Số chẵn chia 2 dư 0.', 'Dùng if/else để chọn kết quả.'], [['4', 'Chan'], ['-3', 'Le'], ['0', 'Chan']]),
    script('Phân loại học lực', 'Nhập điểm từ 0 đến 10. Từ 8: Gioi; từ 6.5: Kha; từ 5: Trung binh; thấp hơn: Yeu.', 'Một số thực.', 'Tên mức xếp loại theo đề.', 'd = float(input())\nif d >= 8:\n    print("Gioi")\nelif d >= 6.5:\n    print("Kha")\nelif d >= 5:\n    print("Trung binh")\nelse:\n    print("Yeu")', ['Xét ngưỡng cao trước.', 'Dùng elif cho các khoảng tiếp theo.'], [['8', 'Gioi'], ['6.5', 'Kha'], ['5', 'Trung binh'], ['4.9', 'Yeu']]),
    script('Năm nhuận', 'Nhập năm. In Nhuan nếu là năm nhuận theo lịch Gregorian, nếu không in Khong nhuan.', 'Một số nguyên năm dương.', 'Nhuan hoặc Khong nhuan.', 'y = int(input())\nif y % 400 == 0 or (y % 4 == 0 and y % 100 != 0):\n    print("Nhuan")\nelse:\n    print("Khong nhuan")', ['Năm chia hết cho 400 luôn nhuận.', 'Nếu chia hết cho 100 nhưng không chia hết cho 400 thì không nhuận.'], [['2000', 'Nhuan'], ['1900', 'Khong nhuan'], ['2024', 'Nhuan'], ['2023', 'Khong nhuan']]),
    script('Ưu đãi thành viên', 'Nhập tổng đơn hàng và hạng thành viên. VIP giảm 10%; thành viên thường giảm 5% nếu đơn từ 500000, còn lại không giảm. In tiền phải trả với 2 chữ số.', 'Dòng 1: giá trị đơn. Dòng 2: VIP hoặc NORMAL.', 'Số tiền phải trả, 2 chữ số thập phân.', 'a = float(input())\nt = input().strip()\nif t == "VIP":\n    r = 0.10\nelif a >= 500000:\n    r = 0.05\nelse:\n    r = 0\nprint(f"{a * (1 - r):.2f}")', ['Xét VIP trước.', 'Dùng elif kiểm tra ngưỡng đơn hàng.'], [['500000\nNORMAL', '475000.00'], ['499999\nNORMAL', '499999.00'], ['100000\nVIP', '90000.00']]),
    script('Phí giao hàng', 'Nhập khoảng cách km. Phí là 20000 đồng cho 2 km đầu và thêm 5000 đồng cho mỗi km vượt quá 2. In phí, làm tròn lên mỗi km lẻ.', 'Một số thực dương: khoảng cách.', 'Một số nguyên: phí giao hàng.', 'import math\nd = float(input())\nif d <= 2:\n    fee = 20000\nelse:\n    fee = 20000 + math.ceil(d - 2) * 5000\nprint(fee)', ['Dùng if/else tách đoạn đến 2 km.', 'math.ceil() làm tròn phần km vượt lên.'], [['1', 20000], ['2', 20000], ['2.1', 25000], ['5', 35000]]),
    script('Lãi hay lỗ', 'Nhập doanh thu và chi phí. In Lai nếu doanh thu lớn hơn chi phí, Hoa von nếu bằng nhau, Lo nếu nhỏ hơn.', '2 dòng: doanh thu và chi phí.', 'Lai, Hoa von hoặc Lo.', 'revenue = float(input())\ncost = float(input())\nif revenue > cost:\n    print("Lai")\nelif revenue == cost:\n    print("Hoa von")\nelse:\n    print("Lo")', ['So sánh doanh thu với chi phí.', 'Dùng ba nhánh if/elif/else.'], [['120\n100', 'Lai'], ['100\n100', 'Hoa von'], ['80\n100', 'Lo']]),
    script('Hoa hồng nhân viên', 'Nhập doanh số. Hoa hồng bằng 2% nếu doanh số dưới 100 triệu, 5% nếu từ 100 đến dưới 500 triệu, 8% nếu từ 500 triệu. In tiền hoa hồng.', 'Một số thực: doanh số (đồng).', 'Tiền hoa hồng, 2 chữ số thập phân.', 's = float(input())\nif s >= 500000000:\n    r = 0.08\nelif s >= 100000000:\n    r = 0.05\nelse:\n    r = 0.02\nprint(f"{s * r:.2f}")', ['Xét mức cao nhất trước.', 'Hoa hồng = doanh số × tỷ lệ.'], [['500000000', '40000000.00'], ['100000000', '5000000.00'], ['50000000', '1000000.00']]),
    script('Phân loại tồn kho', 'Nhập số lượng tồn kho. In Can nhap nếu dưới 10, Sap het nếu từ 10 đến dưới 30, Du hang nếu từ 30.', 'Một số nguyên không âm.', 'Một nhãn theo quy tắc.', 'n = int(input())\nif n < 10:\n    print("Can nhap")\nelif n < 30:\n    print("Sap het")\nelse:\n    print("Du hang")', ['Ngưỡng thứ hai chỉ cần kiểm tra n < 30 vì nhánh trước đã loại n < 10.', 'Xét trường hợp còn lại bằng else.'], [['0', 'Can nhap'], ['10', 'Sap het'], ['29', 'Sap het'], ['30', 'Du hang']]),
    script('Giá sau ưu đãi theo hóa đơn', 'Nhập tổng tiền. Đơn từ 1 triệu giảm 100000 đồng; đơn từ 500000 giảm 30000 đồng; thấp hơn không giảm. In số tiền phải trả.', 'Một số thực không âm.', 'Số tiền phải trả, 2 chữ số thập phân.', 'a = float(input())\nif a >= 1000000:\n    a -= 100000\nelif a >= 500000:\n    a -= 30000\nprint(f"{a:.2f}")', ['Kiểm tra ngưỡng 1 triệu trước.', 'Chỉ áp dụng một mức ưu đãi.'], [['1000000', '900000.00'], ['500000', '470000.00'], ['499999', '499999.00']]),
    script('Kiểm tra quyền mua hàng', 'Nhập tuổi và số tiền trong tài khoản. In Du dieu kien nếu tuổi từ 18 và số dư ít nhất 100000, nếu không in Chua du dieu kien.', '2 dòng: tuổi (số nguyên), số dư.', 'Một nhãn theo đề.', 'age = int(input())\nbalance = float(input())\nif age >= 18 and balance >= 100000:\n    print("Du dieu kien")\nelse:\n    print("Chua du dieu kien")', ['Cả hai điều kiện phải đúng.', 'Nối điều kiện bằng and.'], [['18\n100000', 'Du dieu kien'], ['17\n200000', 'Chua du dieu kien'], ['25\n99999', 'Chua du dieu kien']])
  ],
  loops: [
    script('Bảng nhân', 'Nhập n. In bảng nhân n từ 1 đến 10, mỗi dòng theo dạng n x i = kết_quả.', 'Một số nguyên n.', '10 dòng theo đúng định dạng.', 'n = int(input())\nfor i in range(1, 11):\n    print(f"{n} x {i} = {n * i}")', ['Dùng for i in range(1, 11).', 'Mỗi vòng lặp in một dòng.'], [['2', Array.from({ length: 10 }, (_, i) => `2 x ${i + 1} = ${2 * (i + 1)}`).join('\n')], ['0', Array.from({ length: 10 }, (_, i) => `0 x ${i + 1} = 0`).join('\n')], ['5', Array.from({ length: 10 }, (_, i) => `5 x ${i + 1} = ${5 * (i + 1)}`).join('\n')]]),
    script('Giai thừa', 'Nhập n không âm. Dùng vòng lặp tính n! (0! = 1).', 'Một số nguyên n.', 'Một số nguyên.', 'n = int(input())\nf = 1\nfor i in range(1, n + 1):\n    f *= i\nprint(f)', ['Khởi tạo tích bằng 1.', 'Nhân lần lượt các số từ 1 đến n.'], [['0', 1], ['1', 1], ['5', 120], ['7', 5040]]),
    script('Tổng số lẻ đến n', 'Nhập n không âm. Dùng vòng lặp tính tổng các số lẻ từ 1 đến n.', 'Một số nguyên n.', 'Một số nguyên.', 'n = int(input())\ntotal = 0\nfor i in range(1, n + 1):\n    if i % 2 == 1:\n        total += i\nprint(total)', ['Khởi tạo biến tổng bằng 0.', 'Trong vòng lặp chỉ cộng số lẻ.'], [['0', 0], ['1', 1], ['7', 16], ['10', 25]]),
    script('Đếm chữ số', 'Nhập số nguyên không âm. Dùng while và phép chia nguyên để đếm chữ số; số 0 có một chữ số.', 'Một số nguyên không âm.', 'Một số nguyên.', 'n = int(input())\ncount = 1 if n == 0 else 0\nwhile n > 0:\n    count += 1\n    n //= 10\nprint(count)', ['Mỗi lần // 10 bỏ chữ số cuối.', 'Xử lý riêng n = 0.'], [['0', 1], ['7', 1], ['324', 3], ['100000', 6]]),
    script('Tổng chữ số', 'Nhập số nguyên không âm. Dùng while tính tổng các chữ số.', 'Một số nguyên không âm.', 'Một số nguyên.', 'n = int(input())\ntotal = 0\nwhile n > 0:\n    total += n % 10\n    n //= 10\nprint(total)', ['n % 10 lấy chữ số cuối.', 'Cộng chữ số rồi dùng // 10 để rút ngắn số.'], [['0', 0], ['123', 6], ['9001', 10]]),
    script('Đảo ngược mã số', 'Nhập số nguyên không âm. Dùng vòng lặp tạo số đảo ngược. Ví dụ 120 thành 21.', 'Một số nguyên không âm.', 'Một số nguyên.', 'n = int(input())\nrev = 0\nwhile n > 0:\n    rev = rev * 10 + n % 10\n    n //= 10\nprint(rev)', ['Lấy chữ số cuối bằng % 10.', 'Nhân số đảo hiện tại với 10 rồi cộng chữ số mới.'], [['0', 0], ['123', 321], ['120', 21], ['7', 7]]),
    script('Đếm số chia hết cho k', 'Nhập n và k dương. Đếm các số từ 1 đến n chia hết cho k.', '2 số nguyên: n, k.', 'Một số nguyên.', 'n = int(input())\nk = int(input())\ncount = 0\nfor i in range(1, n + 1):\n    if i % k == 0:\n        count += 1\nprint(count)', ['Duyệt i từ 1 đến n.', 'Nếu i % k == 0 thì tăng biến đếm.'], [['10\n3', 3], ['5\n8', 0], ['12\n4', 3]]),
    script('Tổng dãy Fibonacci không vượt n', 'Tính tổng các số Fibonacci không vượt quá n. Dãy bắt đầu 0, 1, 1, 2, 3,...', 'Một số nguyên n không âm.', 'Một số nguyên.', 'n = int(input())\na, b = 0, 1\ntotal = 0\nwhile a <= n:\n    total += a\n    a, b = b, a + b\nprint(total)', ['Giữ hai số liên tiếp a, b.', 'Cập nhật đồng thời a, b bằng b, a+b.'], [['0', 0], ['1', 2], ['10', 20], ['20', 33]]),
    script('Kiểm tra số nguyên tố bằng vòng lặp', 'Nhập n. In True nếu n là số nguyên tố, ngược lại in False. Không dùng hàm tự định nghĩa.', 'Một số nguyên.', 'True hoặc False.', 'n = int(input())\nis_prime = n >= 2\nfor i in range(2, n):\n    if n % i == 0:\n        is_prime = False\n        break\nprint(is_prime)', ['Số nhỏ hơn 2 không phải số nguyên tố.', 'Thử các ước từ 2 đến n-1; gặp ước thì break.'], [['1', 'False'], ['2', 'True'], ['9', 'False'], ['17', 'True']]),
    script('Số hoàn hảo', 'Nhập n dương. In True nếu n bằng tổng các ước dương nhỏ hơn nó, ngược lại in False.', 'Một số nguyên dương.', 'True hoặc False.', 'n = int(input())\ntotal = 0\nfor i in range(1, n):\n    if n % i == 0:\n        total += i\nprint(total == n)', ['Duyệt i từ 1 đến n-1.', 'Cộng i khi n chia hết cho i.'], [['6', 'True'], ['28', 'True'], ['12', 'False'], ['1', 'False']])
  ],
  functions: [
    func('Bình phương', 'Viết hàm bình_phuong(n) trả về bình phương của n.', 'binh_phuong', 'n', 'def binh_phuong(n):\n    return n ** 2', ['Hàm cần trả về, không chỉ print.', 'Bình phương là n nhân n.'], [['binh_phuong(0)', 0], ['binh_phuong(3)', 9], ['binh_phuong(-4)', 16]]),
    func('Tính tổng hai số', 'Viết hàm tong_hai_so(a, b) trả về tổng hai số.', 'tong_hai_so', 'a, b', 'def tong_hai_so(a, b):\n    return a + b', ['Dùng return để gửi kết quả về nơi gọi.', 'Cộng a và b.'], [['tong_hai_so(2, 3)', 5], ['tong_hai_so(-1, 8)', 7], ['tong_hai_so(0, 0)', 0]]),
    func('Diện tích hình chữ nhật', 'Viết hàm dien_tich_chu_nhat(dai, rong) trả về diện tích.', 'dien_tich_chu_nhat', 'dai, rong', 'def dien_tich_chu_nhat(dai, rong):\n    return dai * rong', ['Diện tích bằng dài nhân rộng.'], [['dien_tich_chu_nhat(4, 3)', 12], ['dien_tich_chu_nhat(2.5, 4)', 10], ['dien_tich_chu_nhat(0, 8)', 0]]),
    func('Giá sau giảm giá', 'Viết hàm gia_sau_giam(gia, phan_tram) trả về giá sau khi giảm.', 'gia_sau_giam', 'gia, phan_tram', 'def gia_sau_giam(gia, phan_tram):\n    return gia * (1 - phan_tram / 100)', ['Đổi phần trăm về dạng thập phân.', 'Trả về giá × (1 - tỷ lệ giảm).'], [['gia_sau_giam(100, 10)', 90], ['gia_sau_giam(50, 0)', 50], ['gia_sau_giam(80, 100)', 0]]),
    func('Kiểm tra số chẵn', 'Viết hàm la_so_chan(n) trả về True nếu n chẵn, ngược lại False.', 'la_so_chan', 'n', 'def la_so_chan(n):\n    return n % 2 == 0', ['Dùng phép chia dư cho 2.', 'Kết quả biểu thức so sánh là bool.'], [['la_so_chan(4)', true], ['la_so_chan(3)', false], ['la_so_chan(0)', true]], 'True hoặc False.'),
    func('Kiểm tra số nguyên tố', 'Viết hàm is_prime(n) trả về True nếu n là số nguyên tố.', 'is_prime', 'n', 'def is_prime(n):\n    if n < 2:\n        return False\n    for i in range(2, int(n ** 0.5) + 1):\n        if n % i == 0:\n            return False\n    return True', ['Số nhỏ hơn 2 không phải số nguyên tố.', 'Chỉ cần thử ước đến căn bậc hai của n.'], [['is_prime(-1)', false], ['is_prime(2)', true], ['is_prime(9)', false], ['is_prime(97)', true]], 'True hoặc False.'),
    func('Giai thừa', 'Viết hàm giai_thua(n) trả về n!, với 0! = 1.', 'giai_thua', 'n', 'def giai_thua(n):\n    result = 1\n    for i in range(1, n + 1):\n        result *= i\n    return result', ['Khởi tạo tích bằng 1.', 'Nhân các số từ 1 đến n.'], [['giai_thua(0)', 1], ['giai_thua(1)', 1], ['giai_thua(5)', 120]]),
    func('Tổng các số lẻ đến n', 'Viết hàm tong_so_le(n) trả về tổng số lẻ dương không vượt quá n.', 'tong_so_le', 'n', 'def tong_so_le(n):\n    total = 0\n    for i in range(1, n + 1, 2):\n        total += i\n    return total', ['range có bước nhảy 2 bắt đầu từ 1.', 'Cộng lần lượt các số lẻ.'], [['tong_so_le(0)', 0], ['tong_so_le(1)', 1], ['tong_so_le(10)', 25]]),
    func('Tổng Fibonacci đến n', 'Viết hàm fibonacci_sum(n) trả về tổng các số Fibonacci không vượt quá n; dãy bắt đầu 0, 1.', 'fibonacci_sum', 'n', 'def fibonacci_sum(n):\n    a, b = 0, 1\n    total = 0\n    while a <= n:\n        total += a\n        a, b = b, a + b\n    return total', ['Giữ hai số liên tiếp trong a và b.', 'Cộng số hiện tại khi nó không vượt n.'], [['fibonacci_sum(0)', 0], ['fibonacci_sum(1)', 2], ['fibonacci_sum(10)', 20]]),
    func('Số hoàn hảo', 'Viết hàm la_so_hoan_hao(n) trả về True nếu n bằng tổng các ước dương nhỏ hơn n.', 'la_so_hoan_hao', 'n', 'def la_so_hoan_hao(n):\n    total = 0\n    for i in range(1, n):\n        if n % i == 0:\n            total += i\n    return total == n', ['Duyệt các số từ 1 đến n-1.', 'Chỉ cộng những ước chia hết n.'], [['la_so_hoan_hao(1)', false], ['la_so_hoan_hao(6)', true], ['la_so_hoan_hao(12)', false], ['la_so_hoan_hao(28)', true]], 'True hoặc False.')
  ]
};

export function makeExercise(topic, difficulty = 'basic', exerciseNumber) {
  const exercises = bank[topic];
  if (!exercises) throw new Error('Chủ đề không hợp lệ.');
  const index = Number.isInteger(exerciseNumber) && exerciseNumber >= 1 && exerciseNumber <= 10 ? exerciseNumber - 1 : randomInt(0, exercises.length);
  const item = structuredClone(exercises[index]);
  const first = item.tests[0], second = item.tests[Math.min(1, item.tests.length - 1)];
  item.topic = topic; item.difficulty = difficulty; item.exerciseNumber = index + 1; item.id = randomUUID(); item.source = 'sample';
  item.examples = [first, second].map(test => ({ input: item.mode === 'function' ? test.expression : test.input, output: test.expected, explanation: 'Kết quả theo bộ test của bài.' }));
  return item;
}

export function makeExam() {
  return ['variables', 'sequences', 'conditions', 'loops', 'functions'].map(topic => makeExercise(topic));
}

